/** 与 electron/shared/map-ids 同源，保证 focus / 投影 id 一致。 */
export {
  MAP_DEFAULT_NEWS_ID,
  MAP_DEFAULT_CHAIN_ID,
  mapIdIsDefaultNews,
  mapIdCreateChain,
  mapIdCreateSource,
  mapIdCreateParse,
  mapIdCreateNews,
  mapIdReadChain,
  mapIdIsSourceRoot,
  mapIdIsScopedNews,
  mapIdCreateSubAgent,
  mapIdReadSubAgent,
  mapIdCreateRoute,
  mapIdCreateClaim,
  mapIdCreateOpinion,
  mapIdCreateEdge,
  mapIdCreateDraftClaim,
  mapIdIsDraftClaim,
  mapIdIsScopedClaim,
  mapIdReadClaimNewsScope,
  mapIdReadClaimSaveIndex,
  mapIdReadDraftIndex,
  mapIdClaimBelongsToNews,
  mapIdReadTransitionScope,
  mapIdReadSubAgentClaim,
  mapIdReadAgentName,
  mapIdCreateInstance,
  mapIdUpdateInstance,
  mapIdReadNodeFocus,
  mapIdReadRouteClaim,
  mapIdReadInterruptFocus,
  DRAFT_CLAIM_PREFIX,
  CLAIM_PREFIX,
} from '../../electron/shared/map-ids'
